name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "583843162@qq.com"
          git config --local user.name "霜刃"
          git remote set-url origin https://ShuangRen:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am "a commit every day, keep your girlfriend far away"
          git push
